# Generated by Django 4.0.3 on 2022-03-08 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
